### ISSUE TITLE
Ozeneu  asshole!!! It'strue!!

### ISSUE THREAD

**Issue by cooler-SAI** [ufologistian/WSLegion#3]
get out!! you asshole!!!! xD))) lol!!! Lier and fucked bitch))

**Comment by Nephelion** [comment]
fuck off please and say BYE

**Comment by cooler-SAI** [comment]
@Nephelion fuck you!

**Comment by Nephelion** [comment]
@cooler-SAI KISS YOUR

**Comment by cooler-SAI** [comment]
@Nephelion  suck mine
